services:
   # Our Phoenix container.
   phoenix:
      # The build parameters for this container.
      build: ./hello
      volumes:
        - hello:/app
      environment:
         # Variables to connect to our Postgres server.
         SECRET_KEY_BASE: AV8AQyfDBDoGEdU2hSRx5by6hAkEsvqb6Ib/yGhAE2H6jVSOf1zMu/Xs/+aEEFjV
         DATABASE_URL: ecto://postgres:postgres@db/hello_dev
         # Hostname of our Postgres container.
         PGHOST: db
      ports:
         # Mapping the port to make the Phoenix app accessible outside of the container.
         - '4000:4000'
      depends_on:
         # The DB container needs to be started before we start this container.
         - db
   db:
      # We use the predefined Postgres image.
      image: postgres:9.6
      environment:
         # Set user/password for Postgres.
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
         # Set a path where Postgres should store the data.
         PGDATA: /var/lib/postgresql/data/pgdata
      restart: always
      ports:
         - '5432:5432'
      volumes:
         - pgdata:/var/lib/postgresql/data
# Define the volumes.
volumes:
   pgdata:
   hello:
